### PR TITLE
Add myself, Antoine Quint, as editor.

### PR DESCRIPTION
**Pull request by graouts**

### CODE REVIEW

**Comment by birtles** [comment]
@graouts It says you need to make IPR commitments before this can be merged.

**Comment by graouts** [comment]
> @graouts It says you need to make IPR commitments before this can be merged.

Right, but I'm not sure how.

**Comment by graouts** [comment]
> @graouts I think you need to join the WICG - can you ask your AC Rep to nominate you?

It's done now. Do you know how to make the ipr checks run again?

**Comment by birtles** [comment]
It's not complaining to me about IPR checks anymore so perhaps it re-ran automatically? Merging.

**Pull request merged**
